In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow import keras 
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [2]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [3]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [4]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [5]:
x=df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y=df['needs_water']

In [6]:
x_min = x.min()
x_max = x.max()
x_scaled = (x - x_min) / (x_max - x_min - 1e-8)

In [7]:
x_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)

In [9]:
model = keras.Sequential([
    layers.Input(shape=(x_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid'),
])

In [10]:
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [12]:
history = model.fit(x_train.values, y_train.values, validation_data=(x_test.values, y_test.values), epochs=100, batch_size=4, verbose=1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.5069 - val_accuracy: 0.7500 - val_loss: 0.5565
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.5063 - val_accuracy: 0.7500 - val_loss: 0.5557
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.5053 - val_accuracy: 0.7500 - val_loss: 0.5551
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.5042 - val_accuracy: 0.7500 - val_loss: 0.5545
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.5028 - val_accuracy: 0.7500 - val_loss: 0.5538
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.5036 - val_accuracy: 0.7500 - val_loss: 0.5532
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.5023 - val_accuracy: 0.7500 - val_loss: 0.5526
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.5016 - val_accuracy: 0.7500 - val_loss: 0.5518
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4998 - val_accuracy: 0.7500 - val_loss: 0.5511
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.5009 - val_accuracy: 0.7500 - val_loss: 0.5503
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4993 - val_accuracy: 0.7500 - val_loss: 0.5496
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.5001 - val_accuracy: 0.7500 - val_loss: 0.5489
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4984 - val_accuracy: 0.7500 - val_loss: 0.5483
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4980 - val_accuracy: 0.7500 - val_loss: 0.5477
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4955 - val_accuracy: 0.7500 - val_loss: 0.5470
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.4967 - val_accuracy: 0.7500 - val_loss: 0.5463
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4955 - val_accuracy: 0.7500 - val_loss: 0.5456
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4933 - val_accuracy: 0.7500 - val_loss: 0.5450
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4928 - val_accuracy: 0.7500 - val_loss: 0.5443
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4932 - val_accuracy: 0.7500 - val_loss: 0.5436
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.4918 - val_accuracy: 0.7500 - val_loss: 0.5430
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4910 - val_accuracy: 0.7500 - val_loss: 0.5422
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9167 - loss: 0.4922 - val_accuracy: 0.7500 - val_loss: 0.5416
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4889 - val_accuracy: 0.7500 - val_loss: 0.5410
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4902 - val_accuracy: 0.7500 - val_loss: 0.5402
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4877 - val_accuracy: 0.7500 - val_loss: 0.5395
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4882 - val_accuracy: 0.7500 - val_loss: 0.5389
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.4875 - val_accuracy: 0.7500 - val_loss: 0.5381
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4856 - val_accuracy: 0.7500 - val_loss: 0.5375
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4851 - val_accuracy: 0.7500 - val_loss: 0.5368
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4841 - val_accuracy: 0.7500 - val_loss: 0.5360
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4833 - val_accuracy: 0.7500 - val_loss: 0.5353
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4831 - val_accuracy: 0.7500 - val_loss: 0.5346
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4837 - val_accuracy: 0.7500 - val_loss: 0.5340
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4812 - val_accuracy: 0.7500 - val_loss: 0.5333
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4820 - val_accuracy: 0.7500 - val_loss: 0.5325
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4814 - val_accuracy: 0.7500 - val_loss: 0.5318
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4794 - val_accuracy: 0.7500 - val_loss: 0.5310
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4788 - val_accuracy: 0.7500 - val_loss: 0.5303
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4779 - val_accuracy: 0.7500 - val_loss: 0.5296
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4771 - val_accuracy: 0.7500 - val_loss: 0.5289
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4765 - val_accuracy: 0.7500 - val_loss: 0.5282
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9167 - loss: 0.4770 - val_accuracy: 0.7500 - val_loss: 0.5275
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4752 - val_accuracy: 0.7500 - val_loss: 0.5268
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4741 - val_accuracy: 0.7500 - val_loss: 0.5261
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4748 - val_accuracy: 0.7500 - val_loss: 0.5254
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4728 - val_accuracy: 0.7500 - val_loss: 0.5247
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4721 - val_accuracy: 0.7500 - val_loss: 0.5240
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4719 - val_accuracy: 0.7500 - val_loss: 0.5233
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4708 - val_accuracy: 0.7500 - val_loss: 0.5226
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4701 - val_accuracy: 0.7500 - val_loss: 0.5219
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.4710 - val_accuracy: 0.7500 - val_loss: 0.5213
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4693 - val_accuracy: 0.7500 - val_loss: 0.5205
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.4695 - val_accuracy: 0.7500 - val_loss: 0.5199
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.4687 - val_accuracy: 0.7500 - val_loss: 0.5193
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4667 - val_accuracy: 0.7500 - val_loss: 0.5185
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4689 - val_accuracy: 0.7500 - val_loss: 0.5179
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4658 - val_accuracy: 0.7500 - val_loss: 0.5171
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4652 - val_accuracy: 0.7500 - val_loss: 0.5164
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4640 - val_accuracy: 0.7500 - val_loss: 0.5157
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4632 - val_accuracy: 0.7500 - val_loss: 0.5150
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4629 - val_accuracy: 0.7500 - val_loss: 0.5143
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4628 - val_accuracy: 0.7500 - val_loss: 0.5135
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4618 - val_accuracy: 0.7500 - val_loss: 0.5127
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4626 - val_accuracy: 0.7500 - val_loss: 0.5120
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4609 - val_accuracy: 0.7500 - val_loss: 0.5112
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4600 - val_accuracy: 0.7500 - val_loss: 0.5105
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4585 - val_accuracy: 0.7500 - val_loss: 0.5098
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4608 - val_accuracy: 0.7500 - val_loss: 0.5090
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.4570 - val_accuracy: 0.7500 - val_loss: 0.5084
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4580 - val_accuracy: 0.7500 - val_loss: 0.5076
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.4558 - val_accuracy: 0.7500 - val_loss: 0.5069
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.4554 - val_accuracy: 0.7500 - val_loss: 0.5062
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9167 - loss: 0.4543 - val_accuracy: 0.7500 - val_loss: 0.5055
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9167 - loss: 0.4541 - val_accuracy: 0.7500 - val_loss: 0.5048
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.4537 - val_accuracy: 0.7500 - val_loss: 0.5042
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.4550 - val_accuracy: 0.7500 - val_loss: 0.5034
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9167 - loss: 0.4524 - val_accuracy: 0.7500 - val_loss: 0.5028
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9167 - loss: 0.4519 - val_accuracy: 0.7500 - val_loss: 0.5021
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9167 - loss: 0.4510 - val_accuracy: 0.7500 - val_loss: 0.5015
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4504 - val_accuracy: 0.7500 - val_loss: 0.5007
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4507 - val_accuracy: 0.7500 - val_loss: 0.5000
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4486 - val_accuracy: 0.7500 - val_loss: 0.4994
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4481 - val_accuracy: 0.7500 - val_loss: 0.4987
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4477 - val_accuracy: 0.7500 - val_loss: 0.4979
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9167 - loss: 0.4467 - val_accuracy: 0.7500 - val_loss: 0.4972
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4461 - val_accuracy: 0.7500 - val_loss: 0.4966
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9167 - loss: 0.4472 - val_accuracy: 0.7500 - val_loss: 0.4959
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9167 - loss: 0.4448 - val_accuracy: 0.7500 - val_loss: 0.4952
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4444 - val_accuracy: 0.7500 - val_loss: 0.4945
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9167 - loss: 0.4434 - val_accuracy: 0.7500 - val_loss: 0.4938
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9167 - loss: 0.4429 - val_accuracy: 0.7500 - val_loss: 0.4931
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4458 - val_accuracy: 0.7500 - val_loss: 0.4923
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9167 - loss: 0.4413 - val_accuracy: 0.7500 - val_loss: 0.4916
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4424 - val_accuracy: 0.7500 - val_loss: 0.4909
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4410 - val_accuracy: 0.7500 - val_loss: 0.4901
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9167 - loss: 0.4394 - val_accuracy: 0.7500 - val_loss: 0.4894
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4395 - val_accuracy: 0.7500 - val_loss: 0.4887
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9167 - loss: 0.4384 - val_accuracy: 0.7500 - val_loss: 0.4881
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9167 - loss: 0.4387 - val_accuracy: 0.7500 - val_loss: 0.4874